FROM node:20 as builder

WORKDIR /app

COPY web/chat/package.json web/chat/package-lock.json ./

RUN npm install --frozen-lockfile

COPY web/chat ./
RUN npm run build

FROM nginx:1.25

COPY --from=builder /app/build /usr/share/nginx/html

COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]