services:
  db:
    image: postgres:17-alpine
    container_name: wg_chat_db
    environment:
      POSTGRES_DB: ${APP_DB_DATABASE}
      POSTGRES_USER: ${APP_DB_USER}
      POSTGRES_PASSWORD: ${APP_DB_PASSWORD}
    ports:
      - ${APP_DB_PORT}:${APP_DB_PORT}
    command: ["postgres", "-c", "port=${APP_DB_PORT}"]
    volumes:
      - ./db_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: wg_chat_redis
    ports:
      - ${APP_REDIS_PORT}:${APP_REDIS_PORT}