syntax = "proto3";

package user.v1;

option go_package = "internal/grpc/gen/userv1;userv1";

message GetUsersRequest {}

message UserItem { int64 id = 1; string username = 2; }

message GetUsersResponse { repeated UserItem users = 1; }

message GetUserByIDRequest { int64 id = 1; }
message GetUserByIDResponse { UserItem user = 1; }

message UpdatePasswordRequest { int64 id = 1; string old_password = 2; string new_password = 3; }
message UpdatePasswordResponse {}

service UserService {
  rpc GetUsers(GetUsersRequest) returns (GetUsersResponse);
  rpc GetUserByID(GetUserByIDRequest) returns (GetUserByIDResponse);
  rpc UpdatePassword(UpdatePasswordRequest) returns (UpdatePasswordResponse);
}

